### ISSUE TITLE
we cannot get the requests or incidents to be sent to a team

### ISSUE THREAD

**Issue by jmoranmontes** [Super-Visions/sv-auto-dispatch#1]
We are trying to use your itop module “sv-auto-dispatch" but we cannot get the requirements or incidents to get dispatched to a team. They remain in  “new state”.
We are in 2.6.1 version.

**Comment by Hipska** [comment]
Did you configure the Dispatch Rules and the Customer Contract?
Is the iTop Cron service running?

**Comment by Hipska** [comment]
From mail communication it turned out that the cron service was not running.
