### ISSUE TITLE
Problème d'application des règles d'affectation 

### ISSUE THREAD

**Issue by lavineuse** [Super-Visions/sv-auto-dispatch#3]
Bonjour, 

Je rencontre un problème avec l'extension sv-auto-dispatch, les règles d'affectation ne s'appliquent pas. J'ai installé l'extension sur la version 3.0.2-1-9957 d'iTop, jusque là pas de soucis. J'ai ensuite créer une règle d'affection en indiquant bien le nom, l'organisation, l'équipe et j'ai défini un timeout à 1m30. Je sélectionne un service, je me positionne sur l'onglet "Contrats client" je clique sur modifier, je sélectionne ma règle d'affectation créée préalablement et j'applique les modifications. Ensuite je créé un ticket dans le service ou la règle d'affectation est définie. Une fois le ticket créé, il ne s'affecte pas automatiquement à l'équipe, il reste en statut "Nouveau" 

![2023-03-14 16_05_37-iTop - Service - Détails de Matériel](https://user-images.githubusercontent.com/73336619/225045748-0b405f57-e889-4773-9f33-a340289916db.png)
 
![2023-03-14 16_14_29-iTop - Demande Utilisateur - Détails de R-000020](https://user-images.githubusercontent.com/73336619/225047606-537c85ca-aca3-4299-a18a-d15579321523.png)

Merci de votre aide

**Comment by Hipska** [comment]
Hi, is the iTop Cron service running?

**Comment by lavineuse** [comment]
Thanks for your feedback. How to start iTop Cron service ?

**Comment by Hipska** [comment]
See the [Background tasks](https://www.itophub.io/wiki/page?id=3_0_0:admin:cron) documentation.
